# Generated by Django 5.2.3 on 2025-06-12 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_comment_is_deleted_post_is_delted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_delted',
            new_name='is_deleted',
        ),
    ]
